### ISSUE TITLE
image embed

### ISSUE THREAD

**Issue by lanoux22** [CloudUnder/mac-signature-installer#2]
First of all, really great project but, 

is their a way in this script to embedded images inside the signature?

**Comment by Manc** [comment]
As you are probably aware, there are two ways you can embed images into an email (including a signature): a link to a server hosted image or as attachment. Both options have positive and negative aspects and it depends what you prefer. I found that linking server hosted images is my preferred option, otherwise every email you send with the signature shows up as an email with attachments on the recipient's end.

The easiest way is, you upload the image to a web server and insert an `<img>` tag into the signature's HTML code.

For the second option you would have to prepare your MIME message with file attachments and link them from your HTML code.

There is a third option – base64 encoded URL strings in your image tags, but quite a few email clients don't support this, so I wouldn't recommend this.

**Comment by lanoux22** [comment]
Ok Manc i understand, i was looking for the second solution with file attachments to be displayed evrywhere without to download images
i will try something under EndOfFormattedSignature

**Comment by Manc** [comment]
Once you get the MIME message into this installer, you should be fine. I think it's outside the scope of the installer script to prepare the signature itself. I therefore close this ticket for now. Good luck!
